version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: DockerFile
    container_name: imy-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - BACKEND_API_URL=http://127.0.0.1:8000/api/
      - BACKEND_WS_URL=ws://127.0.0.1:19000/ws